### ISSUE TITLE
Should findAll() and findAllParallel() produce different outcomes?

### ISSUE THREAD

**Issue by rvprasad** [GPars/GPars#47]
```
import groovyx.gpars.GParsPool
GParsPool.withPool {
 println([1,2,3].collect { if (it % 2) { it } }.findAll())
}

GParsPool.withPool {
 println([1,2,3].collect { if (it % 2) { it } }.findAllParallel())
}
```
produces the following outcome.

> [1, 3]
> Exception thrown
> 
> java.lang.NullPointerException
> 	at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:507)
> 	at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
> 	at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
> 	at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1492)
> 	at groovyx.gpars.extra166y.AbstractParallelAnyArray.allObjects(AbstractParallelAnyArray.java:295)
> 	at groovyx.gpars.extra166y.ParallelArrayWithMapping.all(ParallelArrayWithMapping.java:141)
> 	at groovyx.gpars.pa.GParsPoolUtilHelper.findAllParallelPA(GParsPoolUtilHelper.groovy:200)
> 	at groovyx.gpars.GParsPoolUtil.findAllParallel(GParsPoolUtil.java:621)
> 	at ConsoleScript9$_run_closure2.doCall(ConsoleScript9:7)
> 	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
> 	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
> 	at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
> 	at groovyx.gpars.GParsPool$withExistingPool$2.callStatic(Unknown Source)
> 	at groovyx.gpars.GParsPool$withExistingPool$2.callStatic(Unknown Source)
> 	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
> 	at groovyx.gpars.GParsPool$withPool$1.callStatic(Unknown Source)
> 	at groovyx.gpars.GParsPool$withPool$1.callStatic(Unknown Source)
> 	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
> 	at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
> 	at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
> 	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:100)
> 	at groovyx.gpars.GParsPool$withPool.call(Unknown Source)
> 	at ConsoleScript9.run(ConsoleScript9:6)
> Caused by: java.lang.NullPointerException: Cannot invoke method call() on null object
> 	at groovyx.gpars.pa.GParsPoolUtilHelper$_findAllParallelPA_closure10.doCall(GParsPoolUtilHelper.groovy:200)
> 	at groovyx.gpars.pa.ClosurePredicate.op(ClosurePredicate.java:36)
> 	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OFPap.isSelected(AbstractParallelAnyArray.java:1163)
> 	at groovyx.gpars.extra166y.AbstractParallelAnyArray.leafIndexSelected(AbstractParallelAnyArray.java:264)
> 	at groovyx.gpars.extra166y.PAS$FJSelectAll.compute(PAS.java:1118)
> 	at groovyx.gpars.extra166y.PAS$FJSelectAll.internalPhase0(PAS.java:1133)
> 	at groovyx.gpars.extra166y.PAS$FJSelectAll.compute(PAS.java:1116)
> 	at groovyx.gpars.extra166y.PAS$FJSelectAllDriver.compute(PAS.java:1182)
> 	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
> 	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
> 	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
> 	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
> 	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
> 	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)

**Comment by russel** [comment]
Apologies for the delay getting to this. Hopefully an answer to this conundrum will appear in the next two weeks!

**Comment by pavel-kolesnikov** [comment]
aaaaaaaand it is still reproducible. :D
