### ISSUE TITLE
groovy.lang.MissingMethodException: No signature of method: static groovyx.gpars.forkjoin.GParsPoolUtilHelper.retrieveFJPool()

### ISSUE THREAD

**Issue by wololock** [GPars/GPars#51]
Many tests fail with following exception:

```
groovy.lang.MissingMethodException: No signature of method: static groovyx.gpars.forkjoin.GParsPoolUtilHelper.retrieveFJPool() is applicable for argument types: () values: []

	at groovyx.gpars.forkjoin.GParsPoolUtilHelper.asyncFun(GParsPoolUtilHelper.groovy:47)
	at groovyx.gpars.GParsPoolUtil.asyncFun(GParsPoolUtil.java:164)
	at groovyx.gpars.AsyncFunAnnotationTest.test non-blocking annotation parameters_closure6(AsyncFunAnnotationTest.groovy:108)
	at groovyx.gpars.GParsPool.withExistingPool_closure1(GParsPool.groovy:174)
	at groovyx.gpars.GParsPool.withExistingPool_closure1(GParsPool.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
	at groovyx.gpars.AsyncFunAnnotationTest.test non-blocking annotation parameters(AsyncFunAnnotationTest.groovy:107)
```

I would like to start discussion in this ticket about best alternative for this missing method.

**Comment by russel** [comment]
I am fairly sure I have fixed this in master/HEAD, can I get you to check?
